<a href="https://colab.research.google.com/github/MOHAMMEDAWEZALI2303A51767/AIML-2025_B12/blob/main/AIML_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
lst1=[8,6,9]
array1 = np.array(lst1)
array1

array([8, 6, 9])

In [3]:
type(lst1)

list

In [4]:
type(array1)

numpy.ndarray

In [5]:
list2=[3,2,1]
array2=np.array(list2)
array2

array([3, 2, 1])

In [6]:
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)
print(f" {array2} raised to the power of {array1}:,{array2**array1}")

array2 multiplied by array1:  [24 12  9]
array2 divided by array1:  [0.375      0.33333333 0.11111111]
array2 raised to the power of array1:  [6561   64    1]
 [3 2 1] raised to the power of [8 6 9]:,[6561   64    1]


In [7]:
print("Sine: ",np.sin(array1))
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
print("Exponential: ",np.exp(array1))

Sine:  [ 0.98935825 -0.2794155   0.41211849]
Natural logarithm:  [2.07944154 1.79175947 2.19722458]
Base-10 logarithm:  [0.90308999 0.77815125 0.95424251]
Base-2 logarithm:  [3.        2.5849625 3.169925 ]
Exponential:  [2980.95798704  403.42879349 8103.08392758]


In [8]:
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)

Adding two numpy arrays {array1} and {array2} together: [11  8 10]


In [9]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays [8 6 9] and [3 2 1] together: [11  8 10]
